name: CI

# This workflow triggers on any push to the main branch and on manual trigger
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the runner
      - name: Checkout code
        uses: actions/checkout@v3

      # Install the necessary Python packages listed in requirements.txt
      - name: Install dependencies
        run: make install

      # Format the code using black
      - name: Format code
        run: make format

      # Lint the code using pylint
      - name: Lint code
        run: make lint

      # Run tests using pytest and check code coverage
      - name: Run tests
        run: make test

      # Generate and upload coverage report (optional)
      - name: Upload coverage report
        if: success() # Only upload if the previous steps succeeded
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/ # Adjust if you generate the report in another directory

  # Optional job to enforce branch protection rules
  branch-protection:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' # Only enforce on the main branch

    steps:
      - name: Ensure all required checks have passed
        run: echo "All checks passed, branch protection enforced." # Placeholder for actual logic
        # Integrate a custom script or use GitHub API for more complex rules

# Optional: Send notifications if the workflow fails
notifications:
  failure:
    runs-on: ubuntu-latest

    steps:
      - name: Send failure notification
        run: |
          echo "The CI workflow failed. Please check the logs for details."
          # Here you can integrate with Slack, email, or other notification services
